version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  twilreapi:
    build: ../twilreapi
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      APP_URL_HOST: "http://twilreapi:3000"
      AHN_HOST: "http://adhearsion:8080"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - adhearsion

  adhearsion:
    build: ../somleng-adhearsion
    environment:
      AHN_CORE_HOST: freeswitch
      CALL_PLATFORM_HOST: "http://twilreapi:3000"
    depends_on:
      - freeswitch

  freeswitch:
    build: ../freeswitch-config
    environment:
      - FS_DATABASE_HOST=db
      - FS_EXTERNAL_SIP_IP
      - FS_EXTERNAL_RTP_IP
    ports:
      - "5060:5060/udp"
    depends_on:
      - db
