version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.15
  aws-s3: circleci/aws-s3@1.0.11
executors:
  deploy_website_environment:
    docker:
      - image: 'circleci/python:2.7'

jobs:
  deploy-website:
    working_directory: ~/somleng-website
    executor:
      name: deploy_website_environment

    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure

      - run:
          name: Assume Role
          command: |
              deploy_role=$(aws sts assume-role --role-arn "$AWS_DEPLOY_ROLE_ARN" --role-session-name "Deploy") && \
              echo "export AWS_ACCESS_KEY_ID='$(echo $deploy_role | jq .Credentials.AccessKeyId | xargs)'" >> $BASH_ENV && \
              echo "export AWS_SECRET_ACCESS_KEY='$(echo $deploy_role | jq .Credentials.SecretAccessKey | xargs)'" >> $BASH_ENV && \
              echo "export AWS_SESSION_TOKEN='$(echo $deploy_role | jq .Credentials.SessionToken | xargs)'" >> $BASH_ENV

      - run:
          name: Configure Session Token
          command: |
              aws configure set aws_session_token "$DEPLOY_SESSION_TOKEN" --profile default && \
              cat ~/.aws/config && \
              cat ~/.aws/credentials

      - aws-s3/sync:
          from: public/website
          to: 's3://www.somleng.org'

      - run:
          name: "Invalidate Website CDN"
          command: |
            aws cloudfront create-invalidation --distribution-id $SOMLENG_WEBSITE_DISTRIBUTION_ID --paths /\*

workflows:
  build-deploy:
    jobs:
      - deploy-website:
          context: Somleng
          filters:
            branches:
              only: master
